# See https://github.com/geerlingguy/ansible-collection-mac/tree/master/roles/dock
dockitems_remove:
  - Launchpad
  - Messages
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - TV
  - Music
  - Podcasts
  - News
  - 'App Store'

dockitems_persist:
  - name: Safari
    path: /Applications/Safari.app
    pos: 1
  - name: System Preferences
    path: /System/Applications/System%20Preferences.app
    pos: 2
  - name: Google Chrome
    path: /Applications/Google%20Chrome.app
    pos: 3
  - name: iTerm
    path: /Applications/iTerm.app
    pos: 4
  - name: Visual Studio Code
    path: /Applications/Visual%20Studio%20Code.app
    pos: 5
  - name: Spotify
    path: /Applications/Spotify.app
    pos: 6
  - name: Discord
    path: /Applications/Discord.app
    pos: 7
  - name: Signal
    path: /Applications/Signal.app
    pos: 8
  - name: Slack
    path: /Applications/Slack.app
    pos: 9

# See https://github.com/geerlingguy/ansible-collection-mac/tree/master/roles/homebrew
homebrew_installed_packages:
  - age
  - ansible
  - ansible-lint
  - bash-completion
  - bat
  - biome
  - btop
  - cloc
  - cmake
  - coreutils
  - curl
  - delta
  - deno
  - direnv
  - docker
  - exiftool
  - ffmpeg
  - gcc
  - gh
  - git
  - git-delta
  - git-lfs
  - htop
  - httpie
  - jq
  - just
  - languagetool
  - lazygit
  - mitmproxy
  - nano
  - netcat
  - nim
  - nmap
  - node
  - pixi
  - pnpm
  - pstree
  - qrencode
  - ripgrep
  - ripgrep-all
  - sqlite
  - tmux
  - tree
  - typst
  - vim
  - wget
  - xz
  - yq
  - yt-dlp
  - zsh
  - zsh-syntax-highlighting

homebrew_taps:
  - artginzburg/tap

homebrew_cask_apps:
  - anki
  - discord
  - firefox
  - gitbutler
  - inkscape
  - iterm2
  - karabiner-elements
  - linearmouse
  - michaelvillar-timer
  - mitmproxy
  - notion
  - obsidian
  - orbstack
  - raycast
  - rectangle
  - shottr
  - signal
  - slack
  - spotify
  - telegram
  - ungoogled-chromium
  - ukelele
  - visual-studio-code
  - whatsapp

npm_packages:
  - serve
  - pnpm
  - npm

vscode_extensions:
  - aaron-bond.better-comments # highlights comments matching certain patterns (todo, fixme, etc.)
  - bibhasdn.unique-lines # removes duplicate lines from selection (command)
  - biomejs.biome
  - bradlc.vscode-tailwindcss # some small tailwind support
  - charliermarsh.ruff
  - dbaeumer.vscode-eslint
  - EditorConfig.EditorConfig
  - esbenp.prettier-vscode
  - fallenwood.vimL
  - ftsamoyed.theme-pink-cat-boo
  - github.vscode-github-actions
  - github.vscode-pull-request-github
  - jock.svg
  - kamikillerto.vscode-colorize # colorize hex codes
  - ltex-plus.vscode-ltex-plus
  - max-SS.Cyberpunk@1.2.13
  - mgwg.light-pink-theme
  - mikestead.dotenv
  - ms-azuretools.vscode-containers
  - ms-azuretools.vscode-docker
  - ms-python.debugpy
  - ms-python.mypy-type-checker
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-python.vscode-python-envs
  - ms-vscode.atom-keybindings
  - ms-vscode.cpptools
  - ms-vsliveshare.vsliveshare
  - mvllow.rose-pine
  - myriad-dreamin.tinymist
  - Orta.vscode-twoslash-queries # display typescript types with "// ^?"
  - rebornix.toggle
  - redhat.java
  - redhat.vscode-yaml
  - skellock.just
  - slevesque.vscode-hexdump
  - tombi-toml.tombi
  - tomoki1207.pdf
  - unifiedjs.vscode-mdx@1.2.5
  - vadimcn.vscode-lldb
  - Vallentin.vscode-bnf
  - yoavbls.pretty-ts-errors
  - yummygum.city-lights-theme

ohmyzsh_plugins:
  - { name: git }
  - { name: fzf-zsh-plugin, repo: https://github.com/unixorn/fzf-zsh-plugin.git }
  - { name: zsh-completions, repo: https://github.com/zsh-users/zsh-completions.git }
  - { name: zsh-syntax-highlighting, repo: https://github.com/zsh-users/zsh-syntax-highlighting.git }

config_folder:
  - bat
  - vscode
  - git
  - iTerm2
  - karabiner
  - neofetch
  - sqlite3
  - tmux
# - vim
  - linearmouse
  - mac-xkb-adaptation.bundle

