- name: Ensure iTerm2 is configured to load preferences from custom location
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: LoadPrefsFromCustomFolder
    value: true
    type: boolean
    state: present
- name: Ensure iTerm2 custom preferences location is set
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: PrefsCustomFolder
    value: '~/.config/iterm2'
    type: string
    state: present
