- name: Install global npm packages.
  community.general.npm: # noqa args[module]
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('latest') }}"
    version: "{{ item.version | default(omit) }}"
    global: true
    executable: "{{ item.executable | default(omit) }}"
  loop: "{{ npm_packages }}"
