- name: Ensure oh-my-zsh plugins are present
  ansible.builtin.git: # noqa latest[git]
    repo: "{{ item.repo }}"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/{{ item.name }}"
    depth: 1
  with_items: "{{ ohmyzsh_plugins | selectattr('repo', 'defined') }}"
- name: Ensure custom zsh theme is present
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/files/dots/.oh-my-zsh/custom/themes/robbyrussell-modified.zsh-theme"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/robbyrussell-modified.zsh-theme"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_group }}"
    mode: "preserve"
- name: Ensure custom config is present
  ansible.builtin.copy: # TODO: make sure the unwanted stuff is removed
    src: "{{ playbook_dir }}/files/dots/.oh-my-zsh/custom/{{ item }}"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_group }}"
    mode: "preserve"
  with_items:
    - "aliases.zsh"
    - "functions.zsh"
    - "main.zsh"
    - "applescript"
